spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql57:3306/blogDB?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
#    data: classpath:data.sql
#    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: info
    com.qingfeng.blog: debug
  file: log/blog.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
